# Generated by Django 5.0.4 on 2024-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='customer_username',
            new_name='customer_email',
        ),
    ]
